"""initial migration

Revision ID: 3adb932f11c0
Revises: 
Create Date: 2025-09-09 13:32:14.057195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3adb932f11c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_flag', sa.String(length=100), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('traffic_allocation', sa.JSON(), nullable=False),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('success_metrics', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_test_experiments'))
    )
    op.create_table('memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memories'))
    )
    op.create_table('pending_user_emails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_verified_by_admin', sa.Boolean(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_user_emails')),
    sa.UniqueConstraint('email', name=op.f('uq_pending_user_emails_email'))
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('metric_metadata', sa.JSON(), nullable=True),
    sa.Column('aggregation_period', sa.String(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_metrics'))
    )
    op.create_index('idx_system_metrics_name_timestamp', 'system_metrics', ['metric_name', 'timestamp'], unique=False)
    op.create_index('idx_system_metrics_type_category', 'system_metrics', ['metric_type', 'category'], unique=False)
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_system_metrics_metric_name'), 'system_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token_jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_blacklist'))
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_token_jti'), 'token_blacklist', ['token_jti'], unique=True)
    op.create_index(op.f('ix_token_blacklist_user_id'), 'token_blacklist', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('reset_password_token', sa.String(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_provider', sa.String(), nullable=True),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('pending_email', sa.String(), nullable=True),
    sa.Column('pending_phone_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('is_onboarding', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_users_phone_number')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('ab_test_participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('variant', sa.String(length=100), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('first_exposure_at', sa.DateTime(), nullable=True),
    sa.Column('conversion_events', sa.JSON(), nullable=True),
    sa.Column('participation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['ab_test_experiments.id'], name=op.f('fk_ab_test_participations_experiment_id_ab_test_experiments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ab_test_participations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ab_test_participations'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived', 'deleted')", name=op.f('ck_conversations_valid_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('idx_conversation_user_created', 'conversations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('conversion_funnel_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('time_to_complete_seconds', sa.Integer(), nullable=True),
    sa.Column('step_metadata', sa.JSON(), nullable=True),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversion_funnel_steps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversion_funnel_steps'))
    )
    op.create_index('idx_funnel_steps_completed', 'conversion_funnel_steps', ['completed_at'], unique=False)
    op.create_index('idx_funnel_steps_user_step', 'conversion_funnel_steps', ['user_id', 'step_name'], unique=False)
    op.create_index(op.f('ix_conversion_funnel_steps_id'), 'conversion_funnel_steps', ['id'], unique=False)
    op.create_index(op.f('ix_conversion_funnel_steps_step_name'), 'conversion_funnel_steps', ['step_name'], unique=False)
    op.create_index(op.f('ix_conversion_funnel_steps_user_id'), 'conversion_funnel_steps', ['user_id'], unique=False)
    op.create_table('engagement_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('score_date', sa.DateTime(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('chat_engagement', sa.Float(), nullable=True),
    sa.Column('learning_engagement', sa.Float(), nullable=True),
    sa.Column('project_engagement', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=True),
    sa.Column('session_count', sa.Integer(), nullable=True),
    sa.Column('active_days', sa.Integer(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('calculation_period_days', sa.Integer(), nullable=True),
    sa.Column('calculation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_engagement_scores_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engagement_scores'))
    )
    op.create_index('idx_engagement_scores_overall', 'engagement_scores', ['overall_score'], unique=False)
    op.create_index('idx_engagement_scores_user_date', 'engagement_scores', ['user_id', 'score_date'], unique=False)
    op.create_index(op.f('ix_engagement_scores_id'), 'engagement_scores', ['id'], unique=False)
    op.create_index(op.f('ix_engagement_scores_score_date'), 'engagement_scores', ['score_date'], unique=False)
    op.create_index(op.f('ix_engagement_scores_user_id'), 'engagement_scores', ['user_id'], unique=False)
    op.create_table('feature_usage_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('feature_metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feature_usage_analytics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_usage_analytics'))
    )
    op.create_table('learning_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_metrics_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_metrics'))
    )
    op.create_index('idx_learning_metrics_name_timestamp', 'learning_metrics', ['metric_name', 'timestamp'], unique=False)
    op.create_index('idx_learning_metrics_user_type', 'learning_metrics', ['user_id', 'metric_type'], unique=False)
    op.create_index(op.f('ix_learning_metrics_id'), 'learning_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_learning_metrics_metric_type'), 'learning_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_learning_metrics_timestamp'), 'learning_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_learning_metrics_user_id'), 'learning_metrics', ['user_id'], unique=False)
    op.create_table('learning_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_plans_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_plans'))
    )
    op.create_table('learning_progress',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_progress'))
    )
    op.create_index(op.f('ix_learning_progress_id'), 'learning_progress', ['id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions'))
    )
    op.create_index(op.f('ix_learning_sessions_id'), 'learning_sessions', ['id'], unique=False)
    op.create_table('psychometrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_psychometrics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_psychometrics')),
    sa.UniqueConstraint('user_id', name=op.f('uq_psychometrics_user_id'))
    )
    op.create_index(op.f('ix_psychometrics_id'), 'psychometrics', ['id'], unique=False)
    op.create_table('user_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_events'))
    )
    op.create_index('idx_user_events_session', 'user_events', ['session_id', 'timestamp'], unique=False)
    op.create_index('idx_user_events_type_timestamp', 'user_events', ['event_type', 'timestamp'], unique=False)
    op.create_index('idx_user_events_user_timestamp', 'user_events', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_user_events_event_type'), 'user_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_events_id'), 'user_events', ['id'], unique=False)
    op.create_index(op.f('ix_user_events_session_id'), 'user_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_events_timestamp'), 'user_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('feedback_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_feedback'))
    )
    op.create_table('user_onboarding_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('drop_off_reason', sa.String(length=200), nullable=True),
    sa.Column('step_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_onboarding_analytics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_onboarding_analytics'))
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('learning_style', sa.String(), nullable=True),
    sa.Column('hobbies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_subjects', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('work_style', sa.String(), nullable=True),
    sa.Column('work_preferences', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('career_interests', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('long_term_goals', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('technical_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('soft_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('achievements', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('learning_level', sa.String(), nullable=True),
    sa.Column('completed_projects', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('current_projects', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('skill_levels', sa.JSON(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('cognitive_strengths', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('learning_preferences', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('user_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_metrics', sa.JSON(), nullable=True),
    sa.Column('activity_metrics', sa.JSON(), nullable=True),
    sa.Column('learning_metrics', sa.JSON(), nullable=True),
    sa.Column('collaboration_metrics', sa.JSON(), nullable=True),
    sa.Column('steps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('resources_used', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('challenges_faced', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('solutions_implemented', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('mentor_feedback', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('peer_feedback', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('self_assessment', sa.JSON(), nullable=True),
    sa.Column('final_evaluation', sa.JSON(), nullable=True),
    sa.Column('skills_developed', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('key_learnings', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('next_steps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_projects_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_projects'))
    )
    op.create_index(op.f('ix_user_projects_id'), 'user_projects', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('actions_taken', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index('idx_user_sessions_duration', 'user_sessions', ['duration_seconds'], unique=False)
    op.create_index('idx_user_sessions_user_start', 'user_sessions', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('learning_progress', sa.JSON(), nullable=True),
    sa.Column('recent_activities', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('skill_improvements', sa.JSON(), nullable=True),
    sa.Column('engagement_metrics', sa.JSON(), nullable=True),
    sa.Column('recommended_next_steps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_snapshots_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_snapshots'))
    )
    op.create_index(op.f('ix_user_snapshots_id'), 'user_snapshots', ['id'], unique=False)
    op.create_table('user_support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('satisfaction_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_user_support_tickets_assigned_to_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_support_tickets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_support_tickets')),
    sa.UniqueConstraint('ticket_number', name=op.f('uq_user_support_tickets_ticket_number'))
    )
    op.create_table('feedback_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.String(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_feedback_responses_admin_user_id_users')),
    sa.ForeignKeyConstraint(['feedback_id'], ['user_feedback.id'], name=op.f('fk_feedback_responses_feedback_id_user_feedback')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_responses'))
    )
    op.create_table('messages',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('idx_message_conversation', 'messages', ['conversation_id'], unique=False)
    op.create_index('idx_message_user_created', 'messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('learning_plan_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('phase', sa.Enum('PLANNING', 'IN_PROGRESS', 'REVIEW', 'COMPLETED', name='projectphase'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weeks', sa.String(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('twists', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tips', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('resources', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percentage', sa.INTEGER(), nullable=True),
    sa.Column('project_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['learning_plan_id'], ['learning_plans.id'], name=op.f('fk_projects_learning_plan_id_learning_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('support_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_support_messages_sender_id_users')),
    sa.ForeignKeyConstraint(['ticket_id'], ['user_support_tickets.id'], name=op.f('fk_support_messages_ticket_id_user_support_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages'))
    )
    op.create_table('milestones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_milestones_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('milestones')
    op.drop_table('support_messages')
    op.drop_table('projects')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('idx_message_user_created', table_name='messages')
    op.drop_index('idx_message_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_table('feedback_responses')
    op.drop_table('user_support_tickets')
    op.drop_index(op.f('ix_user_snapshots_id'), table_name='user_snapshots')
    op.drop_table('user_snapshots')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index('idx_user_sessions_user_start', table_name='user_sessions')
    op.drop_index('idx_user_sessions_duration', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_projects_id'), table_name='user_projects')
    op.drop_table('user_projects')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('user_onboarding_analytics')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_timestamp'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_session_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_event_type'), table_name='user_events')
    op.drop_index('idx_user_events_user_timestamp', table_name='user_events')
    op.drop_index('idx_user_events_type_timestamp', table_name='user_events')
    op.drop_index('idx_user_events_session', table_name='user_events')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_psychometrics_id'), table_name='psychometrics')
    op.drop_table('psychometrics')
    op.drop_index(op.f('ix_learning_sessions_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_learning_progress_id'), table_name='learning_progress')
    op.drop_table('learning_progress')
    op.drop_table('learning_plans')
    op.drop_index(op.f('ix_learning_metrics_user_id'), table_name='learning_metrics')
    op.drop_index(op.f('ix_learning_metrics_timestamp'), table_name='learning_metrics')
    op.drop_index(op.f('ix_learning_metrics_metric_type'), table_name='learning_metrics')
    op.drop_index(op.f('ix_learning_metrics_id'), table_name='learning_metrics')
    op.drop_index('idx_learning_metrics_user_type', table_name='learning_metrics')
    op.drop_index('idx_learning_metrics_name_timestamp', table_name='learning_metrics')
    op.drop_table('learning_metrics')
    op.drop_table('feature_usage_analytics')
    op.drop_index(op.f('ix_engagement_scores_user_id'), table_name='engagement_scores')
    op.drop_index(op.f('ix_engagement_scores_score_date'), table_name='engagement_scores')
    op.drop_index(op.f('ix_engagement_scores_id'), table_name='engagement_scores')
    op.drop_index('idx_engagement_scores_user_date', table_name='engagement_scores')
    op.drop_index('idx_engagement_scores_overall', table_name='engagement_scores')
    op.drop_table('engagement_scores')
    op.drop_index(op.f('ix_conversion_funnel_steps_user_id'), table_name='conversion_funnel_steps')
    op.drop_index(op.f('ix_conversion_funnel_steps_step_name'), table_name='conversion_funnel_steps')
    op.drop_index(op.f('ix_conversion_funnel_steps_id'), table_name='conversion_funnel_steps')
    op.drop_index('idx_funnel_steps_user_step', table_name='conversion_funnel_steps')
    op.drop_index('idx_funnel_steps_completed', table_name='conversion_funnel_steps')
    op.drop_table('conversion_funnel_steps')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index('idx_conversation_user_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('chat_sessions')
    op.drop_table('ab_test_participations')
    op.drop_table('users')
    op.drop_index(op.f('ix_token_blacklist_user_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_token_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_metric_name'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_index('idx_system_metrics_type_category', table_name='system_metrics')
    op.drop_index('idx_system_metrics_name_timestamp', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_table('pending_user_emails')
    op.drop_table('memories')
    op.drop_table('ab_test_experiments')
    # ### end Alembic commands ###
