"""Add name, phone_number, message to pending_user_emails

Revision ID: 51565d26bea6
Revises: 398e7963b7b1
Create Date: 2025-10-09 13:27:48.414373

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51565d26bea6'
down_revision = '398e7963b7b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.add_column('pending_user_emails', sa.Column('name', sa.String(), nullable=True))
    op.add_column('pending_user_emails', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('pending_user_emails', sa.Column('message', sa.String(), nullable=True))
    op.create_unique_constraint(op.f('uq_pending_user_emails_phone_number'), 'pending_user_emails', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_pending_user_emails_phone_number'), 'pending_user_emails', type_='unique')
    op.drop_column('pending_user_emails', 'message')
    op.drop_column('pending_user_emails', 'phone_number')
    op.drop_column('pending_user_emails', 'name')
    op.create_table('documents',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###
